export const siteConfig = {
  name: "Junseok Oh (오준석)",
  nickname: "june-oh / RiceBerry",
  // Author name patterns to highlight in publications
  authorHighlight: ["J. Oh", "오준석"],
  title: "Ph.D. Candidate in Computer Science and Engineering",
  description: "Speech Recognition & AI Researcher at Sogang University",
  accentColor: "#0ea5e9", // sky-500 for a clean, professional feel
  social: {
    email: "ohjs@sogang.ac.kr",
    github: "https://github.com/june-oh",
    linkedin: "https://www.linkedin.com/in/junseokoh-riceberry",
    scholar: "https://scholar.google.com/citations?user=W3GNCfgAAAAJ",
    cv: "/june-oh/cv.pdf",
  },
  aboutMe:
    "I am a Ph.D. candidate in Computer Science and Engineering at Sogang University, advised by Prof. Ji-Hwan Kim. My research focuses on End-to-End Automatic Speech Recognition (ASR), Speech Analytics & Assessment, Context-aware & Domain-specific ASR, and the integration of Large Language Models (LLMs) in Speech Technology. I am passionate about building robust, low-latency streaming ASR systems and developing automated speaking assessment frameworks.",
  // Skill icons from skillicons.dev (general programming tools)
  skillIcons: ["py", "c", "pytorch", "linux", "bash", "git", "github", "gitlab", "docker", "vscode"],
  // Speech/ML specific tools (displayed as text badges)
  speechTools: [
    "NVIDIA NeMo",
    "Kaldi",
    "KenLM",
    "Hugging Face Transformers & PEFT",
    "Whisper",
    "Wav2Vec",
    "FastConformer",
  ],
  // Research areas - actual research interests
  researchAreas: [
    { category: "ASR", items: ["Streaming ASR", "Robust ASR", "Context-biasing", "Domain Adaptation"] },
    { category: "Speech + LLM", items: ["Speech LLM", "LLM-based ASR", "Multimodal AI"] },
    { category: "Speech Analytics", items: ["Speaking Assessment", "Dysarthria Analysis", "Audio Event Detection"] },
  ],
  projects: [
    {
      name: "Adapter-Only Speech-LLM Bridging (PhD Dissertation)",
      description:
        "Fully frozen Whisper + Gemma with lightweight adapter-only bridging (0.44% params). 26.8% WER reduction on academic domains via inference-time domain prompting. PAKDD 2026 Accepted (Oral).",
      partner: "",
      period: "Oct 2025 - Present",
      skills: ["PyTorch", "Whisper", "Gemma", "Adapter", "Domain Adaptation"],
    },
    {
      name: "SEAM: Temporal-Semantic Bridging for Speech-LLM",
      description:
        "Encoder-decoder with variable-rate generation via cross-attention. Frozen speech encoder + LLM LoRA. 2.6%/5.2% WER on LibriSpeech, 4.7% on cross-domain TED-LIUM-v2. EACL 2026 Findings Accepted.",
      partner: "",
      period: "May 2025 - Jan 2026",
      skills: ["PyTorch", "Whisper", "LLM", "LoRA", "ASR"],
    },
    {
      name: "Voice/Singing Conversion (SVC)",
      description:
        "End-to-end SVC pipeline: collected ~10h speaker data, extracted vocals via UVR5, trained so-vits-svc & whisper-vits-svc on RTX A5000. Performed voice conversion and singing voice conversion inference.",
      partner: "Personal Project",
      period: "2025",
      skills: ["so-vits-svc", "Whisper", "UVR5", "SVC", "TTS"],
    },
    {
      name: "End-to-End Korean ASR",
      description:
        "Developed universal Korean ASR using hybrid FastConformer RNNT+CTC. Implemented cache-aware streaming for low-latency inference and context biasing for gaming domain vocabulary.",
      partner: "Smilegate",
      period: "2024 - Apr 2025",
      skills: ["NVIDIA NeMo", "FastConformer", "RNNT", "CTC"],
    },
    {
      name: "Telephony (8kHz) End-to-End ASR",
      description:
        "Developed streaming/non-streaming Korean ASR pipelines optimized for 8 kHz telephony using FastConformer-CTC. Implemented dynamic context biasing for domain-shift word-level accuracy.",
      partner: "LOTTE INNOVATE",
      period: "Apr 2024 - Dec 2024",
      skills: ["FastConformer", "CTC", "Streaming ASR"],
    },
    {
      name: "Automated Korean Speaking Assessment (2024)",
      description:
        "Wav2Vec multi-task framework for L2-Korean assessment: jointly models pronunciation, fluency, and content. Combined Conformer-CTC ASR with LLaMa for multi-aspect automated scoring.",
      partner: "Ministry of Culture, Sports and Tourism",
      period: "May 2024 - Dec 2024",
      skills: ["Wav2Vec", "Conformer", "LLaMa"],
    },
    {
      name: "Dialog-based Multi-modal Explainable AI for Dysarthria",
      description:
        "AI framework for dysarthria severity classification with multi-modal explanations. Implemented speech-based explainable diagnostic modules analyzing acoustic and linguistic features.",
      partner: "MSIT / IITP",
      period: "Apr 2022 - Present",
      skills: ["Explainable AI", "Multi-modal", "Speech Analysis"],
    },
    {
      name: "Intelligent Video Content Rating",
      description:
        "Designed sound event detection models for automated video content rating. Fine-tuned Whisper ASR on domain-specific video corpora for robust transcription in diverse acoustic environments.",
      partner: "MSIT",
      period: "2022 - 2024",
      skills: ["Whisper", "Sound Event Detection", "Fine-tuning"],
    },
    {
      name: "Automated Korean Speaking Assessment (2023)",
      description:
        "Built L2-Korean evaluation pipeline combining Conformer-CTC ASR with BERT-based semantic scoring. Developed algorithms to quantify pronunciation accuracy, speech rate, and syntactic correctness.",
      partner: "Ministry of Culture, Sports and Tourism",
      period: "May 2023 - Dec 2023",
      skills: ["Conformer", "CTC", "BERT"],
    },
    {
      name: "Video Story Understanding QA System",
      description:
        "Modified Kaldi sentence-level decoder for sub-1.0 RT real-time video QA. Collected domain-specific audio/text corpora, retrained acoustic/language models for improved QA accuracy on complex narratives.",
      partner: "MSIT",
      period: "Sep 2017 - Dec 2019",
      skills: ["Kaldi", "Language Model", "Real-time ASR"],
    },
  ],
  experience: [
    {
      company: "Sogang University - Auditory Intelligence Lab",
      title: "Ph.D. Student",
      dateRange: "Mar 2022 - Present",
      bullets: [
        "Advisor: Prof. Ji-Hwan Kim",
        "Research on End-to-End ASR, Speech Analytics, and LLM integration in Speech Technology",
        "Developed streaming ASR systems with FastConformer RNNT+CTC architecture",
        "Published papers in EACL, EURASIP JASM, and TIIS journals",
      ],
    },
    {
      company: "Sogang University - Auditory Intelligence Lab",
      title: "M.E. Student",
      dateRange: "Sep 2017 - Aug 2019",
      bullets: [
        "Advisor: Prof. Ji-Hwan Kim",
        "Thesis: Korean Real-Time Automatic Transcription System Using Weakly Labeled Corpus",
        "Modified Kaldi decoder for sub-1.0 RT real-time video QA applications",
        "Collected and curated domain-specific audio/text corpora for ASR optimization",
      ],
    },
  ],
  education: [
    {
      school: "Sogang University",
      degree: "Ph.D. Candidate in Computer Science and Engineering",
      dateRange: "Mar 2022 - Present",
      achievements: [
        "Advisor: Prof. Ji-Hwan Kim",
        "Research Focus: End-to-End ASR, Speech Analytics, LLM Integration",
        "PAKDD 2026 Accepted, Oral Presentation",
        "EACL 2026 Findings Accepted (SEAM)",
      ],
    },
    {
      school: "Sogang University",
      degree: "Master of Engineering in Computer Science and Engineering",
      dateRange: "Sep 2017 - Aug 2019",
      achievements: [
        "Advisor: Prof. Ji-Hwan Kim",
        "Thesis: Korean Real-Time Automatic Transcription System Using Weakly Labeled Corpus",
      ],
    },
    {
      school: "Sogang University",
      degree: "Bachelor of Engineering in Computer Science and Engineering",
      dateRange: "Mar 2010 - Aug 2017",
      achievements: [],
    },
  ],
  // Publications - structured by type
  publications: {
    journals: [
      {
        authors: "J. Oh, J. Nam, and J.-H. Kim",
        title: "HiTCA: Fusing Hierarchical Text and Contextual Audio for Accurate VCR",
        venue: "EURASIP Journal on Audio, Speech, and Music Processing",
        year: "2025",
        note: "SCIE, Under Review",
      },
      {
        authors: "S. Ma, J. Oh, M. Kim, and J.-H. Kim",
        title: "Survey on Deep Learning-based Speech Technologies in Voice Chatbot Systems",
        venue: "KSII Transactions on Internet & Information Systems (TIIS)",
        year: "2025",
        volume: "vol. 19, no. 5, pp. 1406-1440",
        note: "SCIE",
        link: "https://itiis.org/journals/tiis/digital-library/102584",
      },
      {
        authors: "J. Oh, E. Cho, and J.-H. Kim",
        title: "Integration of WFST language model in pre-trained Korean E2E ASR model",
        venue: "KSII Transactions on Internet and Information Systems (TIIS)",
        year: "2024",
        volume: "vol. 18, no. 6, pp. 1692–1705",
        note: "SCIE",
        link: "https://itiis.org/digital-library/99358",
      },
      {
        authors: "S. Seo, J. Oh, E. Cho, H. Park, G. Kim, and J.-H. Kim",
        title: "TP-MobNet: A Two-pass Mobile Network for Low-complexity Classification of Acoustic Scene",
        venue: "Computers, Materials & Continua",
        year: "2022",
        volume: "vol. 73, no. 2",
        note: "SCIE",
        link: "https://www.techscience.com/cmc/v73n2/48321",
      },
      {
        authors: "M. Lim, D. Lee, H. Park, Y. Kang, J. Oh, J.-S. Park, G.-J. Jang, and J.-H. Kim",
        title: "Convolutional neural network based audio event classification",
        venue: "KSII Transactions on Internet and Information Systems (TIIS)",
        year: "2018",
        volume: "vol. 12, no. 6, pp. 2748–2760",
        note: "SCIE",
        link: "https://itiis.org/journals/tiis/digital-library/21791",
      },
    ],
    conferences: [
      {
        authors: "J. Oh and J.-H. Kim",
        title: "Adapter-Only Bridging of Frozen Speech Encoder and Frozen LLM for ASR",
        venue: "Pacific-Asia Conference on Knowledge Discovery and Data Mining (PAKDD)",
        year: "2026",
        note: "Accepted, Oral",
        link: "/june-oh/papers/pakdd2026_adapter_only_asr.pdf",
      },
      {
        authors: "J. Oh and J.-H. Kim",
        title: "SEAM: Bridging the Temporal-Semantic Granularity Gap for LLM-based Speech Recognition",
        venue: "Findings of the Association for Computational Linguistics: EACL 2026",
        year: "2026",
        volume: "pp. 2135–2144",
        note: "Accepted",
        link: "https://aclanthology.org/2026.findings-eacl.112/",
      },
      {
        authors: "J. Oh, H. Park, and J.-H. Kim",
        title: "Speech Intelligibility Prediction of Dysarthria Using Deep Convolutional Networks",
        venue: "Proc. Asia Pacific International Conference on Information Science and Technology (APIC-IST)",
        year: "2023",
        volume: "pp. 236–237",
        link: "/june-oh/papers/apicist2023_dysarthria_oh.pdf",
      },
      {
        authors: "M. Kim, J. Oh, and J.-H. Kim",
        title: "Automated Dysarthria Severity Classification Using Diadochokinetic test and Speech Intelligibility Based on LightGBM",
        venue: "Proc. Asia Pacific International Conference on Information Science and Technology (APIC-IST)",
        year: "2023",
        volume: "pp. 12–13",
        link: "/june-oh/papers/apicist2023_dysarthria_kim.pdf",
      },
      {
        authors: "S. Seo, M. Lim, D. Lee, H. Park, J. Oh, D. J. Rim, and J.-H. Kim",
        title: "Environmental noise robustness for Korean fricatives using speech enhancement generative adversarial networks",
        venue: "Proc. IEEE Int. Conf. Big Data and Smart Computing (BigComp)",
        year: "2019",
        volume: "pp. 1–4",
        link: "https://ieeexplore.ieee.org/document/8679197",
      },
      {
        authors: "S. Seo, D. J. Rim, M. Lim, D. Lee, H. Park, J. Oh, C. Kim, and J.-H. Kim",
        title: "Shortcut connections based deep speaker embeddings for end-to-end speaker verification system",
        venue: "Proc. Interspeech",
        year: "2019",
        volume: "pp. 2928–2932",
        link: "https://www.isca-archive.org/interspeech_2019/seo19_interspeech.html",
      },
    ],
    domestic: [
      {
        authors: "이정필, 장재후, 김지현, 김민섭, 김성준, 김민서, 김하영, 오준석, 정원, 김장연 외",
        title: "음성에 기반한 마비말장애 진단과 설명이 가능한 시스템",
        venue: "정보과학회지",
        year: "2024",
        volume: "vol. 42, no. 4, pp. 45–56",
        note: "KCI",
        link: "https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11753245",
      },
      {
        authors: "H. Park, Y. Kang, M. Lim, D. Lee, J. Oh, and J.-H. Kim",
        title: "LFMMI-based acoustic modeling by using external knowledge",
        venue: "The Journal of the Acoustical Society of Korea",
        year: "2019",
        volume: "vol. 38, no. 5, pp. 607–613",
        note: "KCI",
        link: "https://doi.org/10.7776/ASK.2019.38.5.607",
      },
    ],
  },
  teaching: [
    {
      year: "2024",
      semester: "Fall 2024",
      role: "Teaching Assistant",
      course: "CSE5109/CSEG109/AIEG109/AIE5109",
      title: "Audio Recognition, Synthesis & Transformation (생성형 AI 기반 오디오인식 및 합성/변환)",
      instructor: "Prof. Ji-Hwan Kim",
      school: "Sogang University",
      description: "Lab sessions covering audio processing, deep learning basics, language models, and FastSpeech2 TTS using PyTorch & Colab.",
      github: "https://github.com/june-oh/2024_cseg109",
    },
    {
      year: "2023",
      semester: "Summer 2023",
      role: "Teaching Assistant",
      course: "Samsung AI Academy",
      title: "Deep Learning-based Automatic Speech Recognition",
      instructor: "Prof. Ji-Hwan Kim",
      school: "Sogang University × Samsung Electronics",
      description: "Hands-on ASR tutorial (invited lecture by Prof. Ji-Hwan Kim) covering audio handling, MLP, CTC, Whisper, NVIDIA NeMo finetuning, and WFST using PyTorch & Colab notebooks.",
      github: "https://github.com/june-oh/2023_AI_Academy_ASR",
    },
    {
      year: "2023",
      semester: "Fall 2023",
      role: "Teaching Assistant",
      course: "CSE5109/CSEG109/AIEG109/AIE5109",
      title: "Audio Recognition, Synthesis & Transformation (오디오인식 및 합성변환)",
      instructor: "Prof. Ji-Hwan Kim",
      school: "Sogang University",
      description: "Lab sessions covering audio processing, PyTorch, RNN, CNN, Seq2Seq, and FastSpeech2/VocGAN TTS using PyTorch & Colab.",
      github: "https://github.com/june-oh/cseg109",
    },
    {
      year: "2022",
      semester: "Spring/Fall 2022",
      role: "Teaching Assistant",
      course: "CSE5311/CSEG311/GITA370",
      title: "Conversational User Interface (대화형 사용자 인터페이스개론)",
      instructor: "Prof. Ji-Hwan Kim",
      school: "Sogang University",
      description: "Lab sessions on dialogue systems and conversational AI interface design.",
      github: "",
    },
  ],
  awards: [
    {
      year: "2023",
      competition: "한국어 AI 경진대회",
      track: "Track2-1, 상담 음성인식",
      team: "상담 ONE",
      members: "오준석, 김민서, 남주형",
      award: "장려상",
      organizer: "NIA (한국지능정보사회진흥원)",
    },
    {
      year: "2022",
      competition: "한국어 인공지능 경진대회",
      track: "기업현안 (회의음성)",
      team: "SGCSE",
      members: "오준석, 김하영",
      award: "최우수상 / 네이버 대표 (1위)",
      organizer: "NIA (한국지능정보사회진흥원)",
    },
    {
      year: "2021",
      competition: "음절인식률 측정 알고리즘 개발 대회",
      track: "숫자 포함 패턴발화 음성 데이터셋 활용",
      team: "검은사케동",
      members: "박호성, 오준석, 조은수",
      award: "최우수상 (1위)",
      organizer: "KT alpha",
    },
  ],
  patents: [
    "KR 10-2699607 (B1) - Corpus Construction Service Provision Server and Method (Granted: Aug 2024)",
  ],
  certificates: [
    "NVIDIA Deep Learning Institute - Building Conversational AI Applications (2022)",
  ],
};
